apiVersion: v1
kind: Pod
metadata:
    name: mypod2.0
    labels:
        run: mypod2.0
spec:
    containers:
        - image: s222574652/calculator_ms:latest
          name: calculator-ms
          ports:
              - containerPort: 8080
    dnsPolicy: ClusterFirst
    restartPolicy: Always
