apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeployment
    labels:
        app: myapp
        tier: frontend
spec:
    # modify replicas according to your case
    replicas: 3
    selector:
        matchLabels:
            tier: frontend
    template:
        metadata:
            labels:
                tier: frontend
        spec:
            containers:
                - name: calculator-ms
                  image: s222574652/calculator_ms:latest
                  ports:
                      - containerPort: 8080
